vse: &vse
  docker:
    - image: circleci/node:8.11.3

ansible: &ansible
  docker:
    - image: 'circleci/python:latest'
      environment:
        ANSIBLE_HOST_KEY_CHECKING: no
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *ansible
     steps:
        - attach_workspace:
           at: .
        - ansible-playbook/install
        - run:
            command: sudo pip install ansible boto boto3
        - add_ssh_keys:
            fingerprints:
              - "9f:dc:ff:da:f5:c1:dc:92:79:f7:79:7a:48:cf:fa:eb"
        - ansible-playbook/playbook:
            playbook: ./ansible/ec2_deploy.yml
            playbook-options: --user ubuntu --key-file ./ansible/devops.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: main
