vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     docker:
       - image: ansible/ansible:ubuntu1604
         environment:
           ANSIBLE_HOST_KEY_CHECKING: no
     steps:
        - attach_workspace:
           at: .
        - run:
            name: Install System Packages
            command: pip install --upgrade pip && pip install ansible
        - run: echo $ANSIBLE_VAULT_PASS > ./ansible/.vault-pass.txt
        - run:
           command: ansible-playbook ./ansible/ec2_deploy.yml --vault-password-file=./ansible/.vault-pass.txt --user ubuntu --key-file ./ansible/devops.pem
        - run: rm ./ansible/.vault-pass.txt

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: main
